WebApplication1.Web/Controllers/AuthentificationController.cs
using System;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using WebApplication1.BusinessLogic;
using WebApplication1.Domain.Entities;
using WebApplication1.Web.Models;

namespace WebApplication1.Web.Controllers
{
    public class AuthentificationController : Controller
    {
        private readonly ISession _session;

        public AuthentificationController()
        {
            var bl = new BusinessLogics();
            _session = bl.GetSessionBL();
        }

        public ActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignIn(UserLogin login)
        {
            if (ModelState.IsValid)
            {
                ULoginData data = new ULoginData
                {
                    Username = login.Username,
                    Password = login.Password,
                    LoginDateTime = DateTime.Now
                };

                var userLogin = _session.UserLogin(data);

                if (userLogin.Status)
                {
                    HttpCookie cookie = _session.GenCookie(login.Username);
                    ControllerContext.HttpContext.Response.Cookies.Add(cookie);

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", userLogin.StatusMsg);
                }
            }
            return View();
        }

        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp(UserRegisterModel user)
        {
            if (ModelState.IsValid)
            {
                if (user.Password != user.RePassword)
                {
                    ModelState.AddModelError("", "Password are not the same");
                    return View();
                }

                var data = new URegisterData {
                    Login = user.Login,
                    Password = user.Password,
                    RegisterDate = DateTime.Now
                };

                var registerResponse = _session.UserRegister(data);
                if (registerResponse.Status)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", registerResponse.StatusMsg);
                }
            }
            return View();
        }

        public ActionResult Logout()
        {
            var apiCookie = Request.Cookies["X-KEY"];
            var sessionExist = _session.UserLogout(apiCookie.Value);
            if (sessionExist.Status)
            {
                return new RedirectToRouteResult(new
                    RouteValueDictionary(new { controller = "Home", action = "Index" }));
            }
            else
            {
                ModelState.AddModelError("", sessionExist.StatusMsg);
            }
            return View();
        }
    }
}

WebApplication1.Web/Views/Authentification/SignIn.cshtml
@model WebApplication1.Web.Models.UserLogin
@using System.Web.Optimization
@{
    ViewBag.Title = "SignIn";
}
    <head>
        <link rel="stylesheet" type="text/css" href="~/Content/css/SignIn.css">
    </head>

<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Autentificare</h5>

                    @Html.ValidationSummary(true)
                    <hr class="my-4">
                    @using (Html.BeginForm("SignIn", "Authentification", FormMethod.Post,
                        new { @id = "loginForm", @class = "form-signin" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-label-group">
                            <label for="inputEmail">Adresa de email</label>
                            @Html.TextBoxFor(m => m.Username,
                           new
                                {
                                    type = "email",
                                 placeholder = "Adresa de email",
                                 id = "inputEmail",
                                 name = "inputEmail",
                                 @class = "form-control"
                                })
                        </div>

                        <div class="form-label-group">
                            <label for="inputPassword">Parola</label>
                            @Html.TextBoxFor(m => m.Password,
                           new
                                {
                                    type = "password",
                                 placeholder = "Parola",
                                 id = "inputPassword",
                                 name = "inputPassword",
                                 @class = "form-control"
                                })
                        </div>

                        <div class="custom-control custom-checkbox mb-3">
                            <input type="checkbox" class="custom-control-input" id="customCheck1">
                            <label class="custom-control-label" for="customCheck1">Ține minte parola</label>
                        </div>
                        <hr class="my-4">
                        <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Autentificare</button>

                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/validation/js")

    <script type="text/javascript">
        $(function () {
            $("#loginForm").validate({
                rules: {
                    Username: {
                        required: true
                    },
                    Password: {
                        required: true
                    }
                },
                submitHandler: function (form) {
                    form.submit();
                },
                errorPlacement: function (error, element) {
                    $(element)
                        .closest("form")
                        .find("label[for='" + element.attr("id") + "']")
                        .append(error);
                },
                errorElement: "span"
            });
        });
    </script>
}

WebApplication1.Web/Views/Authentification/SignUp.cshtml
@model WebApplication1.Web.Models.UserRegisterModel
@{
    ViewBag.Title = "Inregistrare";
}
<head>
    <link rel="stylesheet" type="text/css" href="~/Content/css/SignIn.css">
</head>

<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Inregistrare</h5>
                    <hr class="my-4">
                    @Html.ValidationSummary(true)
                    @using (Html.BeginForm("SignUp", "Authentification", FormMethod.Post, new { @id = "registerForm", @class = "form-signup" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-label-group">
                            <label for="inputEmail">Adresa de email</label>
                            @Html.TextBoxFor(m => m.Login, new { type = "email", placeholder = "Adresa de email", id = "email", name = "email", @class = "form-control" })
                        </div>
                        <div class="form-label-group">
                            <label for="inputPassword">Parola</label>
                            @Html.TextBoxFor(m => m.Password, new { type = "password", placeholder = "Parola", id = "password", name = "password", @class = "form-control" })
                        </div>
                        <div class="form-label-group">
                            <label for="inputPassword">Confirma Parola</label>
                            @Html.TextBoxFor(m => m.RePassword, new { type = "password", placeholder = "Confimati parola", id = "repassword", name = "repassword", @class = "form-control" })
                        </div>
                        <hr class="my-4">
                        <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Inregistrare</button>
                    }
                    <div class="text-center">Aveti deja un Cont? <a href="/Authentification/SignIn">Autentificati-va</a></div>
                </div>
            </div>
        </div>
    </div>
</div>